package org.example.app

import kotlinx.serialization.json.Json
import org.example.shared.model.AppVersion
import org.example.shared.model.AppVersionFile

/**
 * The version this build of `app.jar` *is*.
 *
 * Read from the `version.json` resource generated by `:app:generateAppVersionJson` — the same task
 * output that `:packaging` writes to `<install_dir>/app/version.json` for the updater (§9 pt 2).
 * Reading the resource rather than that on-disk file is deliberate:
 *
 * - **The value cannot drift from the jar it describes.** The file on disk belongs to the install
 *   layout and is replaced wholesale by the updater; mid-rollback the two can legitimately
 *   disagree. The resource travels inside the artifact it names.
 * - **No working-directory assumption.** `:app:run`, the preview harnesses and the tests all run
 *   with a CWD that has no `app/version.json`. The repo already carries one CWD assumption (the
 *   marker delete in [main], flagged as fragile in `docs/dev/updater.md`); a second one would be
 *   exercised only in packaged builds, i.e. never in dev.
 *
 * A missing or malformed resource degrades to `0.0.0` rather than throwing — this is display
 * metadata, and no clinical flow depends on it.
 */
object BuildInfo {
    private val json = Json { ignoreUnknownKeys = true }

    val appVersion: AppVersion by lazy {
        val raw = BuildInfo::class.java.getResourceAsStream("version.json")
            ?.use { it.readBytes().decodeToString() }
            ?: return@lazy UNKNOWN
        runCatching { json.decodeFromString(AppVersionFile.serializer(), raw) }
            .getOrNull()
            ?.let { AppVersion.parse(it.appVersion) }
            ?: UNKNOWN
    }

    /** Reported when the generated resource is absent or unparseable. */
    val UNKNOWN: AppVersion = AppVersion(0, 0, 0)
}
