package org.example.app.ui.previews

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.arkivanov.decompose.DefaultComponentContext
import com.arkivanov.essenty.lifecycle.LifecycleRegistry
import org.example.app.domain.DefaultCoroutineDispatchers
import org.example.app.domain.localization.LocalizedStringProvider
import org.example.app.infrastructure.DefaultAppDirectories
import org.example.app.infrastructure.audio.JvmAudioPlaybackService
import org.example.app.infrastructure.audio.JvmWaveformService
import org.example.app.infrastructure.persistence.JsonSessionRepository
import org.example.app.infrastructure.persistence.JsonTimelineRepository
import org.example.app.navigation.DefaultEditorComponent
import org.example.app.ui.EditorContent
import org.example.app.ui.UiLocalization
import org.example.app.ui.theme.ShareTheme
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.name
import kotlin.io.path.readText

/**
 * The editor over a **real recorded session** from `app/data/sessions/`, with the production
 * waveform and playback services — the synthetic previews cannot show whether the position line
 * agrees with audio you can hear, which is the whole point of §8.7's position tracking.
 *
 * It reads sessions but never writes one: `onDone` is a no-op, so pressing Accept does not hand
 * off anywhere (it may still write `timeline_edited.json` if boundaries were moved — that file is
 * regenerated by a normal editor pass, but do not use this on a session you care about).
 * It builds no `AppContainer`, so it does not take `app/data/app.lock` and can run alongside the
 * app.
 */
@Composable
fun EditorLive() {
    val folderName = remember { newestReviewableSession() }

    if (folderName == null) {
        ShareTheme {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Text(
                    text = "No session under app/data/sessions/ has a master recording with a " +
                        "completed VOCAL take to review.",
                    style = MaterialTheme.typography.titleMedium,
                    modifier = Modifier.padding(32.dp),
                )
            }
        }
        return
    }

    val component = remember {
        DefaultEditorComponent(
            componentContext = DefaultComponentContext(LifecycleRegistry()),
            folderName = folderName,
            sessionRepository = JsonSessionRepository(directories),
            timelineRepository = JsonTimelineRepository(directories),
            waveformService = JvmWaveformService(),
            audioPlaybackService = JvmAudioPlaybackService(),
            dispatchers = DefaultCoroutineDispatchers(),
            onDone = {},
        )
    }

    ShareTheme {
        EditorContent(component = component, localization = builtinLocalization)
    }
}

private val directories = DefaultAppDirectories()

/** No config: every `editor.*`/`action.*` key the screen uses resolves from `BuiltinStrings.en`. */
private val builtinLocalization = UiLocalization(LocalizedStringProvider(), "en", null)

/**
 * Newest session folder that the editor will actually find a segment in: a master part on disk,
 * plus a take that was both started and stopped. A cheap text scan rather than a full parse —
 * this only has to pick a folder for a developer to look at.
 */
private fun newestReviewableSession(): String? {
    val sessions = directories.sessionsDir
    if (!Files.isDirectory(sessions)) return null
    return Files.list(sessions).use { stream ->
        stream.filter { Files.isDirectory(it) }
            .filter { hasMasterAudio(it) }
            .filter { it.hasCompletedVocalTake() }
            .sorted(compareByDescending { it.name })
            .findFirst()
            .orElse(null)
    }?.name
}

private fun hasMasterAudio(sessionDir: Path): Boolean {
    val master = sessionDir.resolve("master")
    if (!Files.isDirectory(master)) return false
    return Files.list(master).use { it.anyMatch { file -> file.name.endsWith(".wav") } }
}

private fun Path.hasCompletedVocalTake(): Boolean {
    val timeline = resolve("timeline_original.json")
    val examination = resolve("examination.json")
    if (!Files.isRegularFile(timeline) || !Files.isRegularFile(examination)) return false
    val events = timeline.readText()
    return "START_BUTTON_PRESSED" in events &&
        "STOP_BUTTON_PRESSED" in events &&
        "VOCAL" in examination.readText()
}
